/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RotatingCard: typeof import('./src/components/RotatingCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
